development:
  adapter: postgresql
  encoding: unicode
  database: professional_profile-development
  pool: 5
  port: 5432
  host: localhost

test:
  adapter: postgresql
  encoding: unicode
  database: professional_profile-test
  pool: 5
  port: 5432
  host: localhost